<scene>
 <dimensions>
  <width>300</width>
  <height>300</height> 
 </dimensions>
 <viewport>
  <width>1</width>
  <height>1</height>
  <depth>1</depth>
 </viewport>
 <recursionLimit>6</recursionLimit>
 <supersamples>
  <gridWidth>1</gridWidth>
  <stochasticPoints>0</stochasticPoints> 
 </supersamples>
 <ambient>
  <red>50</red>
  <green>50</green>
  <blue>50</blue>
 </ambient>
 <background>
  <red>255</red>
  <green>255</green>
  <blue>255</blue>
 </background>
 <camera>
  <location>
   <x>0</x>
   <y>0</y>
   <z>0</z>
  </location>
  <rotation>
   <x>0</x>
   <y>0</y>
   <z>0</z>
  </rotation>
 </camera>
 <lights>
  <lamp>
   <name>net.donotturnoff.raytracer.light.Lamp</name>
   <color>
    <red>255</red>
    <green>255</green>
    <blue>255</blue>
   </color>
   <location>
    <x>2</x>
    <y>10</y>
    <z>10</z>
   </location>
  </lamp>
 </lights>
 <entities>
  <sphere>
   <name>Outer</name>
   <location>
    <x>0</x>
    <y>0</y>
    <z>10</z>
   </location>
   <radius>4</radius>
   <material>
    <decorationMap>
     <blockColor>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
      <alpha>20</alpha>
     </blockColor>
    </decorationMap>
    <refractiveIndex>1.01</refractiveIndex>
   </material>
  </sphere>
  <sphere>
   <name>Inner</name>
   <location>
    <x>2.5</x>
    <y>0</y>
    <z>10</z>
   </location>
   <radius>2</radius>
   <material>
    <decorationMap>
     <blockColor>
      <blue>255</blue>
      <alpha>100</alpha>
     </blockColor>
    </decorationMap>
    <refractiveIndex>1.01</refractiveIndex>
   </material>
  </sphere>
  <sphere>
   <name>Behind</name>
   <location>
    <x>1.5</x>
    <y>0</y>
    <z>14</z>
   </location>
   <radius>2</radius>
   <material>
    <decorationMap>
     <blockColor>
      <green>255</green>
     </blockColor>
    </decorationMap>
   </material>
  </sphere>
 </entities>
</scene>
