<scene>
 <dimensions>
  <width>500</width>
  <height>500</height> 
 </dimensions>
 <viewport>
  <width>1</width>
  <height>1</height>
  <depth>1</depth>
 </viewport>
 <recursionLimit>4</recursionLimit>
 <supersamples>
  <gridWidth>1</gridWidth>
  <stochasticPoints>1</stochasticPoints> 
 </supersamples>
 <ambient>
  <red>50</red>
  <green>50</green>
  <blue>50</blue>
 </ambient>
 <background>
  <red>200</red>
  <green>200</green>
  <blue>200</blue>
 </background>
 <camera>
  <location>
   <x>0</x>
   <y>0</y>
   <z>-10</z>
  </location>
  <rotation>
   <x>0</x>
   <y>0</y>
   <z>0</z>
  </rotation>
 </camera>
 <lights>
  <!--<lamp>
   <name>net.donotturnoff.raytracer.light.Lamp</name>
   <color>
    <red>255</red>
    <green>255</green>
    <blue>255</blue>
   </color>
   <location>
    <x>-3</x>
    <y>2</y>
    <z>6</z>
   </location>
  </lamp>-->
  <lamp>
   <name>net.donotturnoff.raytracer.light.Lamp in the midst of everything</name>
   <color>
    <red>255</red>
    <green>200</green>
    <blue>200</blue>
   </color>
   <location>
    <x>0</x>
    <y>5</y>
    <z>14</z>
   </location>
  </lamp>
 </lights>
 <entities>
  <sphere>
   <name>Lens</name>
   <location>
    <x>0</x>
    <y>0</y>
    <z>10</z>
   </location>
   <radius>3</radius>
   <material>
    <decorationMap>
     <blockColor>
      <red>170</red>
      <green>170</green>
      <blue>255</blue>
      <alpha>50</alpha>
     </blockColor>
    </decorationMap>
    <refractiveIndex>1.02</refractiveIndex>
   </material>
  </sphere>
  <sphere>
   <name>net.donotturnoff.raytracer.entity.Sphere</name>
   <location>
    <x>4.5</x>
    <y>0</y>
    <z>10.5</z>
   </location>
   <radius>2</radius>
   <material>
    <decorationMap>
     <blockColor>
      <red>100</red>
      <green>150</green>
      <blue>255</blue>
     </blockColor>
    </decorationMap>
    <ambientMap>
     <blockColor>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
     </blockColor>
    </ambientMap>
    <specularMap>
     <blockColor>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
     </blockColor>
    </specularMap>
    <shineMap>
     <constantValue>
      <value>100</value>
     </constantValue>
    </shineMap>
   </material>
  </sphere>
  <sphere>
   <name>Mirror sphere</name>
   <location>
    <x>-5</x>
    <y>5</y>
    <z>25</z>
   </location>
   <radius>8</radius>
   <material>
    <decorationMap>
     <blockColor>
      <red>150</red>
      <green>150</green>
      <blue>170</blue>
     </blockColor>
    </decorationMap>
    <reflectionMap>
     <constantValue>
      <value>255</value>
     </constantValue>
    </reflectionMap>
   </material>
  </sphere>
  <sphere>
   <name>net.donotturnoff.raytracer.entity.Sphere behind</name>
   <location>
    <x>-2</x>
    <y>0</y>
    <z>17</z>
   </location>
   <radius>3</radius>
   <material>
    <decorationMap>
     <checker>
      <color1>
       <red>0</red>
       <green>255</green>
       <blue>255</blue>
      </color1>
      <color2>
       <red>255</red>
       <green>0</green>
       <blue>0</blue>
      </color2>
      <checkerSize>2</checkerSize>
      <width>20</width>
      <height>20</height>
     </checker>
    </decorationMap>
    <specularMap>
     <checker>
      <color1>
       <red>0</red>
       <green>255</green>
       <blue>255</blue>
      </color1>
      <color2>
       <red>255</red>
       <green>0</green>
       <blue>0</blue>
      </color2>
      <checkerSize>2</checkerSize>
      <width>20</width>
      <height>20</height>
     </checker>
    </specularMap>
    <shineMap>
     <constantValue>
      <value>100</value>
     </constantValue>
    </shineMap>
   </material>
  </sphere>
  <!--<plane>
   <normal>
    <component>0</component>
    <component>1</component>
    <component>0</component>
   </normal>
   <point>
    <component>0</component>
    <component>1</component>
    <component>0</component>
   </point>
   <material>
    <decorationMap>
     <blockColor>
      <red>150</red>
      <green>150</green>
      <blue>150</blue>
     </blockColor>
    </decorationMap>
    <reflectionMap>
     <constantValue>
      <value>255</value>
     </constantValue>
    </reflectionMap>
   </material>
  </plane>-->
 </entities>
</scene>
